# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples


## USER DEFINED GLOBAL VARIABLES ##

# How many character to display if we go with very long directory path from 
# right to left,
DIR_STR_WIDTH=20


# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
# don't overwrite GNU Midnight Commander's setting of `ignorespace'.
HISTCONTROL=$HISTCONTROL${HISTCONTROL+:}ignoredups
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

shopt -s cdspell

# make less more friendly for non-text input files, see lesspipe(1)
#[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'



    # User Specific aliases.
    alias mq='cd /mnt/data/company/mquotient/'
    alias glyfix='cd /mnt/data/company/mquotient/workspace/glyfix; activate; cd glyfix-unstable'
    alias cgw='cd /mnt/data/company/mquotient/workspace/alcatel/cgw/'
    alias projects='cd /mnt/data/projects/'
    alias coursera='cd /mnt/data/projects/coursera/'
    alias backup='cd /mnt/backup/'
    alias money='cd /mnt/data/projects/workspace/money_manager'

    alias github='cd /mnt/data/projects/github/'
    alias blog='cd /mnt/data/projects/github/haridas.github.com/'

    # Python virtual env alias 
    alias activate='test -d ENV && source ./ENV/bin/activate || echo "No Virtualenv in the current folder"'
    alias mkenv='test -d ENV && echo "Already exists" || virtualenv --system-site-packages ENV; activate'


fi

# some more ls aliases
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

##### Amazon Web Service Settings.

PATH=$PATH:/mnt/data/company/mquotient/aws/ec2-api-tools-1.5.5.0/bin:/mnt/data/company/mquotient/aws/AutoScaling-1.0.49.1/bin

# - env settings.
export EC2_HOME=/mnt/data/company/mquotient/aws/ec2-api-tools-1.5.5.0
export AWS_AUTO_SCALING_HOME=/mnt/data/company/mquotient/aws/AutoScaling-1.0.49.1
export JAVA_HOME=/usr/lib/jvm/java-6-sun-1.6.0.26
export AWS_CLOUDWATCH_HOME=$EC2_HOME
export EC2_PRIVATE_KEY=~/.ssh/pk-CZ7O3MN6KGVJGWC33P3NPGOYTKD6UOJT.pem
export EC2_CERT=~/.ssh/cert-CZ7O3MN6KGVJGWC33P3NPGOYTKD6UOJT.pem


### Scala Global Settings.
PATH=$PATH:/mnt/data/projects/coursera/scala/packages/sbt/bin
# play framework command.
PATH=$PATH:/mnt/data/softwares/play-2.0.4


### Go Language environment settings.
export GOROOT=/mnt/data/projects/pgrm_demos/go/packages/go-source/
PATH=$PATH:$GOROOT/bin
 

export PERL_LOCAL_LIB_ROOT="/root/perl5";
export PERL_MB_OPT="--install_base /root/perl5";
export PERL_MM_OPT="INSTALL_BASE=/root/perl5";
export PERL5LIB="/root/perl5/lib/perl5/x86_64-linux-gnu-thread-multi:/root/perl5/lib/perl5";
export PATH="/root/perl5/bin:$PATH";


export WORKON_HOME="~/.virtualenvs"
source /usr/local/bin/virtualenvwrapper.sh
